### ISSUE TITLE
headview在刷新时，切换fragment时导致的NullPointerException

### ISSUE THREAD

**Issue by jamin918** [lcodecorex/TwinklingRefreshLayout#3]
Process: com.lcodecore.twinklingrefreshlayout, PID: 17990
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                                          at com.lcodecore.tkrefreshlayout.header.SinaRefreshView.onPullReleasing(SinaRefreshView.java:88)
                                                                                          at com.lcodecore.tkrefreshlayout.TwinklingRefreshLayout$SimplePullListener.onPullDownReleasing(TwinklingRefreshLayout.java:731)
                                                                                          at com.lcodecore.tkrefreshlayout.TwinklingRefreshLayout$6.onAnimationUpdate(TwinklingRefreshLayout.java:331)
                                                                                          at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
                                                                                          at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:949)
                                                                                          at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
                                                                                          at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
                                                                                          at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
                                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:959)
                                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:969)
                                                                                          at android.animation.ObjectAnimator.start(ObjectAnimator.java:829)

刷新后释放状态时更新文字提示时报空指针。

**Comment by lcodecorex** [comment]
收到，稍后修复。

**Comment by lcodecorex** [comment]
Hello！我测试之后没有发现问题的复现，能具体描述一下情况吗？或者可以发消息到我的邮箱lcodecore@163.com  谢谢配合！

**Comment by jamin918** [comment]
谢谢回复， 我后面试了很多次也没有发现报错了， 不知道这个错误是怎么发生的，没有复原出来

**Comment by lcodecorex** [comment]
嗯。确实发现控件有一些没有考虑到的地方，稍后会修复。

**Comment by jamin918** [comment]
/**
     * 加载更多结束
     */
    public void finishLoadmore() {
        if (pullListener != null) pullListener.onFinishLoadMore();
        if (mChildView != null) {
            animChildView(0f);
            mChildView.scrollBy(0, (int) mBottomHeight);
            mBottomLayout.postDelayed(new Runnable() {
                @Override
                public void run() {
                    if (mBottomLayout != null) {
                        mBottomLayout.getLayoutParams().height = 0;
                        mBottomLayout.requestLayout();
                    }
                }
            }, 250);
        }
        isLoadingmore = false;
    }
发现mChildView.scrollBy(0, (int) mBottomHeight);这行代码在listview、gridview控件中，请求第二页数据成功后，结束加载更多时最底部不是第二页数据的第一条item，显示的是footer, 点击屏幕后，footer不再显示。在RecyclerView中没有这个问题。麻烦有空看一下，谢谢。ps: 我暂时改成了mChildView.scrollBy(0, 0);不显示下一屏数据的第一条item.

**Comment by lcodecorex** [comment]
好的。这个我优化下
