### ISSUE TITLE
mHeadLayout.removeAllViewsInLayout(); --> null

### ISSUE THREAD

**Issue by mecobean** [lcodecorex/TwinklingRefreshLayout#48]
```
错误日志：
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.removeAllViewsInLayout()' on a null object reference
	at com.lcodecore.tkrefreshlayout.TwinklingRefreshLayout$1.run(TwinklingRefreshLayout.java:219)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

```
--------------------

```
框架源码：
 /**
     * 设置头部View
     */
    public void setHeaderView(final IHeaderView headerView) {
        if (headerView != null) {
            post(new Runnable() {
                @Override
                public void run() {
                    mHeadLayout.removeAllViewsInLayout();
                    mHeadLayout.addView(headerView.getView());
                }
            });
            mHeadView = headerView;
        }
    }
```

**Comment by sisel** [comment]
onAttachedToWindow 此前没有被回调

**Comment by sisel** [comment]
不解为何要在onAttachedToWindow中初始化:mHeadLayout,mExtraHeadLayout,mBottomLayout

**Comment by lcodecorex** [comment]
@sisel 因为在构造函数中初始化mHeadLayout,mExtraHeadLayout,mBottomLayout，可滑动View最后被inflate进来=getChildAt(3)。而在onAttachedToWindow方法中可滑动View始终为getChildAt(0)。目前已修改。

**Comment by sisel** [comment]
已修改?好像没看到commit,应该怎么避免这个bug呢?

**Comment by lcodecorex** [comment]
在构造函数中初始化mHeadLayout,mExtraHeadLayout,mBottomLayout，然后在onFinishInflate方法中获取到可滑动View:
```java
@Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        //获得子控件
        //TODO 可能引入新问题，fixedHeader显示异常
        mChildView = getChildAt(3);

        cp.init();
    }
```

没有提交是因为引入了一点小问题

**Comment by sisel** [comment]
thx 
期待更新~

**Comment by lcodecorex** [comment]
v1.06已修复，感谢反馈！
