### ISSUE TITLE
7.0系统 demo闪退了 机型是华为P9

### ISSUE THREAD

**Issue by yanyiqun001** [lcodecorex/TwinklingRefreshLayout#57]

**Comment by lcodecorex** [comment]
我测了没蹦呀。可以看到日志吗？

**Comment by yanyiqun001** [comment]
03-15 15:53:37.263 18888-18888/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.lcodecore.twinklingrefreshlayout, PID: 18888
                                                   android.os.StrictMode$StrictModeViolation: policy=327711 violation=2
                                                       at android.os.StrictMode.executeDeathPenalty(StrictMode.java:1556)
                                                       at android.os.StrictMode.-wrap3(StrictMode.java)
                                                       at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolation(StrictMode.java:1549)
                                                       at android.os.StrictMode$AndroidBlockGuardPolicy$1.run(StrictMode.java:1427)
                                                       at android.os.Handler.handleCallback(Handler.java:755)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
