### ISSUE TITLE
删除报空指针了

### ISSUE THREAD

**Issue by lenmoyouziJiangjun** [lcodecorex/TwinklingRefreshLayout#69]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.removeAllViewsInLayout()' on a null object reference
	at com.lcodecore.tkrefreshlayout.TwinklingRefreshLayout$1.run(TwinklingRefreshLayout.java:219)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)

**Comment by lcodecorex** [comment]
这个问题之前好像出现过，使用的场景是什么样的呢？

**Comment by lcodecorex** [comment]
@lenmoyouziJiangjun 感谢反馈！新版正在内测，可以来帮忙看一下情况吗？qq群202640706
